version: '3.8'

services:
  frontend:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8080
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    image: rust:1.89.0
    working_dir: /app
    volumes:
      - ../backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - target-cache:/app/target
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=0
    command: sh -c "cargo build --release && ./target/release/api"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  cargo-cache:
  cargo-git:
  target-cache: